import org.junit.Assert;
import org.junit.Test;

public class Part6Test {
    Part6 part6 = new Part6();
    String dna = "AGTCTCTACGACGGATGTATGATACAAAACAGCGTGCAAAAATGCCGACGTGGCTATGCATCTGTTTAATTAAGGAATCCGAGCGGCGAACCCGCACG" +
            "CATGCACGGCTCTGCGATCCATGGACCGAGGGTTAGGATGAGCCCCTAATTGACGCATGCCCATAAGCCGATCGTGTACTACCTTAGGACAGAATTTTCAGAA" +
            "CTAGGTGTAGAATATAACGTGAACCATAGTGTTTGACACTCGTTCCATATTGATTATGCCTCTACCAGATGACCACAGCTTCTTCCTCTATATCTTTCGAGAA" +
            "GCTAATTCCCCTTGTTAGCGGGCAACTCAATAACCCGCACGACGACCCCCGCGTTAGGTCAAATACTATAAAATTTTGGGATTGGCCTACTATTCCGTGAACA" +
            "CTTCGAGCACGCTTTGACGGAGGGAAAATTTCGAAGATCTCTCTATTTGTGGTTTCCTCGTATTTACGTAAGGATTTTTCGCGCTAGCAAGTTTGATCTTGTG" +
            "GACTGCGGACTTGGTGTAGCATGCTATGTTTTCTTCTTCAGTATATTGAGGTAACCGTCCCCGACCGACCGTGATAGGAACTAGGTTACCGGTAATAGGTTAA" +
            "TTACACAGAGCTTGTAACACCCGACATGGGCACCTGCCGCTCCGCTGCGTCGCCTAATGTTAACCACCCGACCCGGATGCATGTACATACGTTTAAGTCCAAA" +
            "ATAAGGCCGCGGACTCCCCAGCAGTACGTCTTACCAAATCACHELLOACTTCAAAGTAAGCTCGTAGATCGATTTCGTGGGATATAATTTCGGCACTGAAATAAGAAC" +
            "CGTCGCGTTCCGCCTGGTAAACTACGCAGCTGCCCAGGTCGACGGATGCTTGGTTCGCAAATCTAAGCCGTAGGGGCTTGGATGATCCCGCCGTTTGCACTCC" +
            "GATTTATAGAATAGTGTGAGTACCTGACGAAATACGGGTAGTTCGCACTATCTGGTTGTGATTACCCATAGTCGGCGG";

    @Test
    public void testHowMany() throws Exception {
        int result1 = part6.howMany("T", dna);
        Assert.assertEquals(265, result1);

        int result2 = part6.howMany("a", dna);
        Assert.assertEquals(254, result2);

        int result3 = part6.howMany("5", dna);
        Assert.assertEquals(0, result3);

        int result4 = part6.howMany("TAA", dna);
        Assert.assertEquals(22, result4);

        int result5 = part6.howMany("hello", dna);
        Assert.assertEquals(1, result5);
    }
}
