import org.junit.Assert;
import org.junit.Test;

public class Part5Test {

    Part5 part5 = new Part5();
    String dna1 = "AGTCTCTACGACGGATGTATGATACAAAACAGCGTGCAAAAATGCCGACGTGGCTATGCATCTGTTTAATTAAGGAATCCGAGCGGCGAACCCGCACG" +
            "CATGCACGGCTCTGCGATCCATGGACCGAGGGTTAGGATGAGCCCCTAATTGACGCATGCCCATAAGCCGATCGTGTACTACCTTAGGACAGAATTTTCAGAA" +
            "CTAGGTGTAGAATATAACGTGAACCATAGTGTTTGACACTCGTTCCATATTGATTATGCCTCTACCAGATGACCACAGCTTCTTCCTCTATATCTTTCGAGAA" +
            "GCTAATTCCCCTTGTTAGCGGGCAACTCAATAACCCGCACGACGACCCCCGCGTTAGGTCAAATACTATAAAATTTTGGGATTGGCCTACTATTCCGTGAACA" +
            "CTTCGAGCACGCTTTGACGGAGGGAAAATTTCGAAGATCTCTCTATTTGTGGTTTCCTCGTATTTACGTAAGGATTTTTCGCGCTAGCAAGTTTGATCTTGTG" +
            "GACTGCGGACTTGGTGTAGCATGCTATGTTTTCTTCTTCAGTATATTGAGGTAACCGTCCCCGACCGACCGTGATAGGAACTAGGTTACCGGTAATAGGTTAA" +
            "TTACACAGAGCTTGTAACACCCGACATGGGCACCTGCCGCTCCGCTGCGTCGCCTAATGTTAACCACCCGACCCGGATGCATGTACATACGTTTAAGTCCAAA" +
            "ATAAGGCCGCGGACTCCCCAGCAGTACGTCTTACCAAATCACACTTCAAAGTAAGCTCGTAGATCGATTTCGTGGGATATAATTTCGGCACTGAAATAAGAAC" +
            "CGTCGCGTTCCGCCTGGTAAACTACGCAGCTGCCCAGGTCGACGGATGCTTGGTTCGCAAATCTAAGCCGTAGGGGCTTGGATGATCCCGCCGTTTGCACTCC" +
            "GATTTATAGAATAGTGTGAGTACCTGACGAAATACGGGTAGTTCGCACTATCTGGTTGTGATTACCCATAGTCGGCGG";

    String dna2 = "TGTAGGCGGAGCATGTCACACCTTCGCTGCTTTCCTACAGGCGTCACTAAAAGCAAGCTATCTGTAATATATGTCGACATAACGACGTACCCGCCAC" +
            "TGCCGCATCAGTCTCCTAGGCCTTAAATTACTTACGAGGACACAGCCACGCTTGAGTTATTCTACATAGTGGGATAAAGCGACAGATTTGAGTCTCACATCCT" +
            "GTGCTTATCGTAAAGACACACGAACCCTCGCCGTGGCCAAGGCAAAAACCGGCCATGAACCTTGTCTCGAATAACAGTAATATATGAAGACCATGTAACGATT" +
            "CCCAGTTTTAGACATGTCTCGGTAGGCGTGACAGTGGCCTCATTTCTGATGTCGCGACCGGAACTCGAATAAGCACCCTCCGAGGTTGGTGGGCTCACTAGTG" +
            "TTGCGCCACGAGGTCAATGCCCGCCGACGGCCACCAAGTCGTCAATGGCCGACGGAGCCTCAATACTTTCGTCAGTGGTTGTAAAACGTGCTGAGTTACCGGC" +
            "GACCCGTTCGCAACATTCGAGCGAACGATTTTCACTAGAAAAAATAGAGGGCTGCCGAATGTAATCATATTCACGAAGCTGTTGCCTATAACTTGAACGATTT" +
            "ATAGATGAATGCGGCCGCGTGTACAGCGCCCCGTCGCTTAACGACGCCAATCCTGAGATATACGGGGTTGATTTGCCCACGTCAAGGATACATGTTCGGGTTT" +
            "CATACTTCAATCCTCATGCGTTACCGAATCGAACCTGTGTGATTTCCATCCTATTTGCACGAATGTCGCGCAAACGCAGATCGGGTCCTTGCCGTAAAATCGG" +
            "ATTTTCAGGTGACGAGGAGCTTATAGCGCCTCTCTCAACACAGTGGATGGAGTAGATTGCCACAGGAGCCACCAGTCGTTATTATTTCAAGTGAAGGGTATTG" +
            "GTGAATGCTGTAAACAGGATCATGAATTGACCGGACTAGAATCCCGGTTCTATGGACACGTTAAATATTGTTACGGCGT";

    @Test
    public void testFindGene() {
        String result1 = part5.findGene(dna1, 78);
        Assert.assertEquals("ATGCACGGCTCTGCGATCCATGGACCGAGGGTTAGGATGAGCCCCTAA", result1);

        String result2 = part5.findGene(dna2, 134);
        Assert.assertEquals("ATGAACCTTGTCTCGAATAACAGTAATATATGA", result2);
    }

    @Test
    public void testFindStopCodon() {

        int result1 = part5.findStopCodon(dna1, dna1.indexOf("ATG"), "TAA");
        int result2 = part5.findStopCodon(dna1, dna1.indexOf("ATG"), "TGA");
        int result3 = part5.findStopCodon(dna1, dna1.indexOf("ATG"), "TAG");
        int result4 = part5.findStopCodon(dna2, dna2.indexOf("ATG"), "TAA");
        int result5 = part5.findStopCodon(dna2, dna2.indexOf("ATG"), "TGA");
        int result6 = part5.findStopCodon(dna2, dna2.indexOf("ATG"), "TAG");
        Assert.assertEquals(161, result1);
        Assert.assertEquals(251, result2);
        Assert.assertEquals(131, result3);
        Assert.assertEquals(120, result4);
        Assert.assertEquals(255, result5);
        Assert.assertEquals(870, result6);
    }

    @Test
    public void testPrintAllGene() {
        Assert.assertTrue(part5.printAllGene(dna1));
    }
}